name: xformer_pruning

dependencies:
  - python==3.8
  - pip
  - matplotlib
  - opencv
  - cudnn=8
  - cudatoolkit
  - pip:
    - torch==1.8.0+cu111
    - torchvision==0.9.0+cu111
    - torchaudio==0.8.0
    - transformers
    - tqdm
    - torchtext==0.9.0
    - cupy-cuda111
    - tensorboard
    - spacy
    - numpy
    - seaborn
    - scipy 
    - scikit-learn
    - datasets







